include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore

linter:
  rules:
    avoid_print: false
    prefer_single_quotes: true
